export const PACKAGES: Package[] = [
  {
    id: 'orbit-1',
    name: 'Orbit Stellar',
    price: 50,
    dailyReturn: 1.5,
    totalReturn: 75,
    duration: 50,
    cap: 75,
    level: 1,
    isActive: true,
    icon: 'orbit-stellar',
    color: '#00E5FF',
  },
  {
    id: 'orbit-2',
    name: 'Orbit Nova',
    price: 100,
    dailyReturn: 3.5,
    totalReturn: 175,
    duration: 50,
    cap: 175,
    level: 2,
    isActive: true,
    icon: 'orbit-nova',
    color: '#7B61FF',
  },
  {
    id: 'orbit-3',
    name: 'Orbit Pulse',
    price: 250,
    dailyReturn: 10,
    totalReturn: 500,
    duration: 50,
    cap: 500,
    level: 3,
    isActive: true,
    icon: 'orbit-pulse',
    color: '#00FFB2',
  },
  {
    id: 'orbit-4',
    name: 'Orbit Vertex',
    price: 500,
    dailyReturn: 22.5,
    totalReturn: 1125,
    duration: 50,
    cap: 1125,
    level: 4,
    isActive: true,
    icon: 'orbit-vertex',
    color: '#FFB800',
  },
  {
    id: 'orbit-5',
    name: 'Orbit Apex',
    price: 1000,
    dailyReturn: 50,
    totalReturn: 2500,
    duration: 50,
    cap: 2500,
    level: 5,
    isActive: true,
    icon: 'orbit-apex',
    color: '#FF5C7A',
  },
  {
    id: 'orbit-6',
    name: 'Orbit Quantum',
    price: 2500,
    dailyReturn: 137.5,
    totalReturn: 6875,
    duration: 50,
    cap: 6875,
    level: 6,
    isActive: true,
    icon: 'orbit-quantum',
    color: '#00E5FF',
  },
  {
    id: 'orbit-7',
    name: 'Orbit Infinity',
    price: 5000,
    dailyReturn: 300,
    totalReturn: 15000,
    duration: 50,
    cap: 15000,
    level: 7,
    isActive: true,
    icon: 'orbit-infinity',
    color: '#7B61FF',
  },
  {
    id: 'orbit-8',
    name: 'Orbit Genesis',
    price: 10000,
    dailyReturn: 650,
    totalReturn: 32500,
    duration: 50,
    cap: 32500,
    level: 8,
    isActive: true,
    icon: 'orbit-genesis',
    color: '#00FFB2',
  },
];

export const NAV_LINKS = [
  { href: '/dashboard', label: 'Dashboard', icon: 'LayoutDashboard' },
  { href: '/packages', label: 'Packages', icon: 'Package' },
  { href: '/my-orbit', label: 'My Orbit', icon: 'Orbit' },
  { href: '/matrix', label: 'Matrix Explorer', icon: 'GitBranch' },
  { href: '/earnings', label: 'Earnings', icon: 'TrendingUp' },
  { href: '/upgrade-vault', label: 'Upgrade Vault', icon: 'Vault' },
  { href: '/withdrawals', label: 'Withdrawals', icon: 'Wallet' },
  { href: '/transactions', label: 'Transactions', icon: 'ArrowLeftRight' },
  { href: '/referrals', label: 'Referrals', icon: 'Users' },
  { href: '/apex-pool', label: 'Apex Pool', icon: 'Trophy' },
  { href: '/leaderboard', label: 'Leaderboard', icon: 'BarChart3' },
  { href: '/notifications', label: 'Notifications', icon: 'Bell' },
  { href: '/profile', label: 'Profile', icon: 'UserCircle' },
  { href: '/support', label: 'Support Center', icon: 'LifeBuoy' },
];

export const ADMIN_NAV_LINKS = [
  { href: '/admin', label: 'Dashboard', icon: 'LayoutDashboard' },
  { href: '/admin/users', label: 'User Management', icon: 'Users' },
  { href: '/admin/packages', label: 'Package Management', icon: 'Package' },
  { href: '/admin/matrix', label: 'Matrix Manager', icon: 'GitBranch' },
  { href: '/admin/earnings', label: 'Earnings Manager', icon: 'TrendingUp' },
  { href: '/admin/withdrawals', label: 'Withdraw Management', icon: 'Wallet' },
  { href: '/admin/apex-pool', label: 'Apex Pool Manager', icon: 'Trophy' },
  { href: '/admin/referrals', label: 'Referral Manager', icon: 'Users' },
  { href: '/admin/announcements', label: 'Announcements', icon: 'Megaphone' },
  { href: '/admin/transactions', label: 'Transaction Logs', icon: 'ArrowLeftRight' },
  { href: '/admin/settings', label: 'Settings', icon: 'Settings' },
  { href: '/admin/security', label: 'Security Center', icon: 'Shield' },
];

export const USDT_ADDRESS = '0x55d398326f99059fF775485246999027B3197955';
export const TREASURY_WALLET = '0x0000000000000000000000000000000000000000';
export const BSC_RPC_URL = 'https://bsc-dataseed.binance.org/';
export const BSC_CHAIN_ID = 56;

import type { Package } from '@/types';
